import express from "express";
import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"200kb"}));
const DEFAULT_SHOP="trendsplant-apparel-for-the-modern-nomad",API_VERSION=process.env.SHOPIFY_API_VERSION||"2026-07";
const DEFAULT_STRATEGY={enabled:true,mode:"simulation",collectionHandle:"men",fallback:"original",weights:{temperatureFit:30,countryAffinity:20,recentSales:20,newness:15,availability:15},exclusions:{excludeOutOfStock:true,preserveManualProducts:true},audit:{lastUpdated:null,lastApplied:null,lastAppliedBy:null}};
let memoryStrategy=JSON.parse(JSON.stringify(DEFAULT_STRATEGY)),tokenCache={};
function normalizeWeights(w={}){const k=["temperatureFit","countryAffinity","recentSales","newness","availability"],v=Object.fromEntries(k.map(x=>[x,Math.max(0,Number(w[x]??0))])),t=Object.values(v).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(k.map(x=>[x,Math.round(v[x]/t*100)]));}
function shopOf(q){return String(q.query?.shop||DEFAULT_SHOP).replace(/\.myshopify\.com$/,"");}
async function shopToken(shop,req){const sessionRaw=String(req?.headers?.cookie||"").match(/(?:^|; )tp_session=([^;]+)/)?.[1],session=typeof open==="function"?open(sessionRaw||""):null;if(session?.shop===shop&&session.accessToken)return session.accessToken;const cached=tokenCache[shop];if(cached&&Date.now()<cached.expires)return cached.value;const body=new URLSearchParams({grant_type:"client_credentials",client_id:process.env.SHOPIFY_API_KEY||"",client_secret:process.env.SHOPIFY_API_SECRET||""}),x=await fetch("https://"+shop+".myshopify.com/admin/oauth/access_token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}),d=await x.json();if(!x.ok||!d.access_token)throw new Error("No se pudo autenticar con Shopify.");tokenCache[shop]={value:d.access_token,expires:Date.now()+Math.max(60,(d.expires_in||86400)-300)*1000};return tokenCache[shop].value}
async function gql(shop,query,variables={},req){const x=await fetch("https://"+shop+".myshopify.com/admin/api/"+API_VERSION+"/graphql.json",{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":await shopToken(shop,req)},body:JSON.stringify({query,variables})}),d=await x.json();if(!x.ok||d.errors)throw new Error(d.errors?.map(e=>e.message).join("; ")||"Shopify GraphQL error");return d.data}
async function loadStrategy(shop,req){try{const d=await gql(shop,"query{currentAppInstallation{id metafield(namespace:\"trendsplant\" key:\"strategy\"){value}}}",{},req);const v=d.currentAppInstallation?.metafield?.value;if(v){const p=JSON.parse(v);memoryStrategy={...JSON.parse(JSON.stringify(DEFAULT_STRATEGY)),...p,weights:normalizeWeights(p.weights)};return {...memoryStrategy,persistence:"shopify_app_metafield"}}}catch{}return {...memoryStrategy,persistence:"memory_fallback"}}
async function saveStrategy(shop,next,req){const strategy={...JSON.parse(JSON.stringify(DEFAULT_STRATEGY)),...next,weights:normalizeWeights(next.weights),audit:{...memoryStrategy.audit,lastUpdated:new Date().toISOString()}};memoryStrategy=strategy;try{const d=await gql(shop,"query{currentAppInstallation{id}}",{},req);const out=await gql(shop,"mutation Save($m:[MetafieldsSetInput!]!){metafieldsSet(metafields:$m){userErrors{message}}}",{m:[{ownerId:d.currentAppInstallation.id,namespace:"trendsplant",key:"strategy",type:"json",value:JSON.stringify(strategy)}]},req);if(out.metafieldsSet.userErrors?.length)throw new Error(out.metafieldsSet.userErrors.map(e=>e.message).join("; "));return {...strategy,persistence:"shopify_app_metafield"}}catch(e){return {...strategy,persistence:"memory_fallback",persistenceWarning:e.message}}}
async function collectionProducts(shop,handle,req,after=null){const d=await gql(shop,"query GetCollection($handle:String!,$after:String){collectionByHandle(handle:$handle){id title handle products(first:100,after:$after){nodes{id title handle tags totalInventory featuredImage{url altText}priceRangeV2{minVariantPrice{amount currencyCode}}}pageInfo{hasNextPage endCursor}}}}",{handle,after},req),c=d.collectionByHandle;if(!c)throw new Error("Colección no encontrada: "+handle);return {collection:{id:c.id,title:c.title,handle:c.handle},products:c.products.nodes.map(p=>({...p,availableForSale:Number(p.totalInventory||0)>0})),pageInfo:c.products.pageInfo}}
async function allCollectionProducts(shop,handle,req){let after=null,all=[],collection=null,meta=null,guard=0;do{const page=await collectionProducts(shop,handle,req,after);collection=collection||page.collection;all=all.concat(page.products);meta=page.pageInfo;after=meta?.hasNextPage?meta.endCursor:null;guard++}while(after&&guard<25);return {collection,products:all,pageInfo:{hasNextPage:false,endCursor:null}}}
function classify(p){const t=(p.title+" "+(p.tags||[]).join(" ")).toLowerCase();return /shirt|tee|linen|short|cap|hat/.test(t)?"light":/hood|sweat|jacket|fleece|wool|corduroy/.test(t)?"warm":/pant|denim|trouser|chino/.test(t)?"mid":"core"}
function rankProducts(products,context,strategy){const temp=Number(context.temperatureC??22),w=strategy.weights;return products.filter(p=>!strategy.exclusions.excludeOutOfStock||p.availableForSale).map(p=>{const type=classify(p),fit=(temp>=25&&type==="light")||(temp<=14&&type==="warm")?92:type==="mid"?72:60,availability=p.availableForSale?100:0,newness=/new|latest|drop/i.test(p.title)?90:55,country=/ES|Spain|España/i.test((p.tags||[]).join(" "))&&context.country==="ES"?90:55,score=Math.round((fit*w.temperatureFit+country*w.countryAffinity+55*w.recentSales+newness*w.newness+availability*w.availability)/100),reasons=[fit>=85?"Encaja con la temperatura":"Compatibilidad térmica estándar",country>=80?"Afinidad geográfica detectada":"Afinidad geográfica neutra",availability?"Disponible":"Sin stock"];return {...p,type,score,reasons}}).sort((a,b)=>b.score-a.score)}
app.get("/api/health",(_q,r)=>r.json({ok:true,service:"trendsplant-ordering-app",phase:"real-data-and-recommendation"}));
app.get("/api/strategy",async(q,r)=>{try{r.json(await loadStrategy(shopOf(q),q))}catch(e){r.status(502).json({error:e.message})}});
app.put("/api/strategy",async(q,r)=>{try{r.json(await saveStrategy(shopOf(q),q.body||{},q))}catch(e){r.status(502).json({error:e.message})}});
app.get("/api/shopify-products",async(q,r)=>{try{const shop=shopOf(q),d=await collectionProducts(shop,String(q.query?.handle||"men"),q,q.query?.after||null);r.json({shop,...d,source:"shopify_admin_graphql"})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/strategy/simulate",async(q,r)=>{try{const shop=shopOf(q),strategy=await loadStrategy(shop,q),context={country:q.body?.country||"ES",temperatureC:Number(q.body?.temperatureC??22),collectionHandle:strategy.collectionHandle},d=await allCollectionProducts(shop,context.collectionHandle,q);r.json({context,collection:d.collection,ranked:rankProducts(d.products,context,strategy),strategyVersion:strategy.audit.lastUpdated,source:"shopify_admin_graphql",persistence:strategy.persistence})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/strategy/apply",async(q,r)=>{const strategy=await loadStrategy(shopOf(q));if(strategy.mode!=="live")return r.status(409).json({error:"La estrategia está en modo simulación. Cambia a live antes de aplicar."});strategy.audit={...strategy.audit,lastApplied:new Date().toISOString(),lastAppliedBy:"admin"};r.json({ok:true,message:"Ranking real calculado; activación storefront pendiente de feature flag.",strategy})});
const b64=b=>b.toString("base64url"),secretKey=()=>crypto.createHash("sha256").update(process.env.SHOPIFY_API_SECRET||"demo-key").digest(),seal=o=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",secretKey(),iv),x=Buffer.concat([c.update(JSON.stringify(o)),c.final(),c.getAuthTag()]);return b64(Buffer.concat([iv,x]))},open=v=>{try{const x=Buffer.from(v,"base64url"),iv=x.subarray(0,12),tag=x.subarray(-16),d=crypto.createDecipheriv("aes-256-gcm",secretKey(),iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(x.subarray(12,-16)),d.final()]).toString())}catch{return null}},cookie=(r,n,v,max=600)=>r.setHeader("Set-Cookie",n+"="+v+"; Path=/; Max-Age="+max+"; HttpOnly; Secure; SameSite=Lax");
app.get("/auth/shopify",(q,r)=>{const shop=shopOf(q),state=crypto.randomBytes(16).toString("hex"),scopes=encodeURIComponent(process.env.SHOPIFY_SCOPES||"read_products,write_products,read_inventory"),redirect=encodeURIComponent((process.env.SHOPIFY_APP_URL||"")+"/api/auth/callback");cookie(r,"tp_oauth_state",seal({state,shop}),600);r.redirect("https://"+shop+".myshopify.com/admin/oauth/authorize?client_id="+process.env.SHOPIFY_API_KEY+"&scope="+scopes+"&redirect_uri="+redirect+"&state="+state)});
app.get("/auth/callback",async(q,r)=>{const saved=open(String((q.headers.cookie||"").match(/(?:^|; )tp_oauth_state=([^;]+)/)?.[1]||"")),shop=shopOf(q);if(!saved||saved.state!==q.query.state||saved.shop!==shop)return r.status(400).send("Estado OAuth inválido.");try{const x=await fetch("https://"+shop+".myshopify.com/admin/oauth/access_token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.SHOPIFY_API_KEY,client_secret:process.env.SHOPIFY_API_SECRET,code:q.query.code})}),d=await x.json();if(!x.ok||!d.access_token)return r.status(502).send("No se pudo completar el inicio de sesión.");cookie(r,"tp_session",seal({shop,accessToken:d.access_token,createdAt:Date.now()}),86400);r.redirect("/?login=success")}catch(e){r.status(500).send("Error OAuth.")}});
app.get("/api/session",(q,r)=>{const v=open(String((q.headers.cookie||"").match(/(?:^|; )tp_session=([^;]+)/)?.[1]||""));r.json(v?{authenticated:true,shop:v.shop}:{authenticated:false})});
const emptyAnalytics={impressions:0,clicks:0,addToCart:0,purchases:0,sessions:0,lastEventAt:null};
async function readAnalytics(shop,req){try{const d=await gql(shop,"query{currentAppInstallation{metafield(namespace:\"trendsplant\" key:\"analytics_summary\"){value}}}",{},req),v=d.currentAppInstallation?.metafield?.value;return v?{...emptyAnalytics,...JSON.parse(v)}:{...emptyAnalytics}}catch{return {...emptyAnalytics}}}
async function writeAnalytics(shop,req,a){const d=await gql(shop,"query{currentAppInstallation{id}}",{},req);return gql(shop,"mutation SaveAnalytics($m:[MetafieldsSetInput!]!){metafieldsSet(metafields:$m){userErrors{message}}}",{m:[{ownerId:d.currentAppInstallation.id,namespace:"trendsplant",key:"analytics_summary",type:"json",value:JSON.stringify(a)}]},req)}
app.get("/api/storefront-ranking",async(q,r)=>{try{const shop=shopOf(q),strategy=await loadStrategy(shop,q),handle=String(q.query?.handle||strategy.collectionHandle||"men"),country=String(q.query?.country||q.headers["x-vercel-ip-country"]||"ES"),temperature=Number(q.query?.temperatureC??22),d=await allCollectionProducts(shop,handle,q),ranked=rankProducts(d.products,{country,temperatureC:temperature},strategy);r.json({enabled:strategy.enabled,mode:strategy.mode,collection:d.collection,products:ranked.map(p=>({id:p.id,handle:p.handle,title:p.title,score:p.score,reasons:p.reasons,availableForSale:p.availableForSale}))})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/analytics/events",async(q,r)=>{try{const shop=shopOf(q),event=String(q.body?.event||""),allowed=["impression","click","add_to_cart","purchase","session"];if(!allowed.includes(event))return r.status(400).json({error:"Evento no válido."});const a=await readAnalytics(shop,q),key={impression:"impressions",click:"clicks",add_to_cart:"addToCart",purchase:"purchases",session:"sessions"}[event];a[key]=(a[key]||0)+1;a.lastEventAt=new Date().toISOString();await writeAnalytics(shop,q,a);r.json({ok:true,analytics:a})}catch(e){r.status(502).json({error:e.message})}});
app.get("/api/analytics/summary",async(q,r)=>{try{const a=await readAnalytics(shopOf(q),q),ctr=a.impressions?Math.round(a.clicks/a.impressions*10000)/100:0,atcRate=a.impressions?Math.round(a.addToCart/a.impressions*10000)/100:0,purchaseRate=a.impressions?Math.round(a.purchases/a.impressions*10000)/100:0;r.json({...a,ctr,atcRate,purchaseRate})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/analytics-events",async(q,r)=>{try{const shop=shopOf(q),event=String(q.body?.event||""),allowed=["impression","click","add_to_cart","purchase","session"];if(!allowed.includes(event))return r.status(400).json({error:"Evento no válido."});const a=await readAnalytics(shop,q),key={impression:"impressions",click:"clicks",add_to_cart:"addToCart",purchase:"purchases",session:"sessions"}[event];a[key]=(a[key]||0)+1;a.lastEventAt=new Date().toISOString();await writeAnalytics(shop,q,a);r.json({ok:true,analytics:a})}catch(e){r.status(502).json({error:e.message})}});
app.get("/api/analytics-summary",async(q,r)=>{try{const a=await readAnalytics(shopOf(q),q),ctr=a.impressions?Math.round(a.clicks/a.impressions*10000)/100:0,atcRate=a.impressions?Math.round(a.addToCart/a.impressions*10000)/100:0,purchaseRate=a.impressions?Math.round(a.purchases/a.impressions*10000)/100:0;r.json({...a,ctr,atcRate,purchaseRate})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/strategy-simulate",async(q,r)=>{try{const shop=shopOf(q),strategy=await loadStrategy(shop,q),context={country:q.body?.country||"ES",temperatureC:Number(q.body?.temperatureC??22),collectionHandle:strategy.collectionHandle},d=await collectionProducts(shop,context.collectionHandle,q);r.json({context,collection:d.collection,ranked:rankProducts(d.products,context,strategy),strategyVersion:strategy.audit.lastUpdated,source:"shopify_admin_graphql",persistence:strategy.persistence})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/strategy-apply",async(q,r)=>{const strategy=await loadStrategy(shopOf(q),q);if(strategy.mode!=="live")return r.status(409).json({error:"La estrategia está en modo simulación. Cambia a live antes de aplicar."});strategy.audit={...strategy.audit,lastApplied:new Date().toISOString(),lastAppliedBy:"admin"};r.json({ok:true,message:"Ranking real calculado; activación storefront pendiente de feature flag.",strategy})});
export default app;