import express from "express";
import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"200kb"}));
let strategy={enabled:true,mode:"simulation",collectionHandle:"men",fallback:"original",weights:{temperatureFit:30,countryAffinity:20,recentSales:20,newness:15,availability:15},exclusions:{excludeOutOfStock:true,preserveManualProducts:true},audit:{lastUpdated:null,lastApplied:null,lastAppliedBy:null}};
function normalizeWeights(w={}){const k=["temperatureFit","countryAffinity","recentSales","newness","availability"],v=Object.fromEntries(k.map(x=>[x,Math.max(0,Number(w[x]||0))])),t=Object.values(v).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(k.map(x=>[x,Math.round(v[x]/t*100)]));}
const b64=b=>b.toString("base64url"),key=()=>crypto.createHash("sha256").update(process.env.SHOPIFY_API_SECRET||"demo-key").digest(),seal=o=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key(),iv);const x=Buffer.concat([c.update(JSON.stringify(o)),c.final(),c.getAuthTag()]);return b64(Buffer.concat([iv,x]));},open=v=>{try{const x=Buffer.from(v,"base64url"),iv=x.subarray(0,12),tag=x.subarray(-16),d=crypto.createDecipheriv("aes-256-gcm",key(),iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(x.subarray(12,-16)),d.final()]).toString())}catch{return null}},cookie=(r,n,v,max=600)=>r.setHeader("Set-Cookie",`${n}=${v}; Path=/; Max-Age=${max}; HttpOnly; Secure; SameSite=Lax`);
app.get("/api/health",(_q,r)=>r.json({ok:true,service:"trendsplant-ordering-app"}));
app.get("/api/strategy",(_q,r)=>r.json(strategy));
app.put("/api/strategy",(q,r)=>{strategy={...strategy,...q.body,weights:normalizeWeights(q.body?.weights||strategy.weights),audit:{...strategy.audit,lastUpdated:new Date().toISOString()}};r.json(strategy);});
app.post("/api/strategy/simulate",(q,r)=>{const c={country:q.body?.country||"ES",temperatureC:Number(q.body?.temperatureC??22),collectionHandle:strategy.collectionHandle},s=[["Essential T-Shirt","light",78],["Hooded Oversized Sweatshirt","warm",72],["Easy Denim Pants","mid",75],["Timber Corduroy Cap","accessory",68]],ranked=s.map(([title,type,baseScore],i)=>({id:"sample-"+(i+1),title,type,score:Math.min(100,baseScore+Math.round((((c.temperatureC>=25&&type==="light")||(c.temperatureC<=14&&type==="warm")?22:type==="mid"?8:0)*strategy.weights.temperatureFit/100)))})).sort((a,b)=>b.score-a.score);r.json({context:c,ranked,strategyVersion:strategy.audit.lastUpdated});});
app.post("/api/strategy/apply",(_q,r)=>{if(strategy.mode!=="live")return r.status(409).json({error:"La estrategia está en modo simulación. Cambia a live antes de aplicar."});strategy.audit={...strategy.audit,lastApplied:new Date().toISOString(),lastAppliedBy:"admin"};r.json({ok:true,message:"Aplicación preparada para el conector Shopify.",strategy});});
app.get("/auth/shopify",(q,r)=>{const shop=String(q.query.shop||"").replace(/\.myshopify\.com$/,"");if(!shop||!process.env.SHOPIFY_API_KEY||!process.env.SHOPIFY_APP_URL)return r.status(400).send("Indica una tienda Shopify válida.");const state=crypto.randomBytes(16).toString("hex"),scopes=encodeURIComponent(process.env.SHOPIFY_SCOPES||"read_products,write_products,read_inventory"),redirect=encodeURIComponent(process.env.SHOPIFY_APP_URL+"/auth/callback");cookie(r,"tp_oauth_state",seal({state,shop}),600);r.redirect(`https://${shop}.myshopify.com/admin/oauth/authorize?client_id=${process.env.SHOPIFY_API_KEY}&scope=${scopes}&redirect_uri=${redirect}&state=${state}`);});
app.get("/auth/callback",async(q,r)=>{const saved=open(String((q.headers.cookie||"").match(/(?:^|; )tp_oauth_state=([^;]+)/)?.[1]||"")),shop=String(q.query.shop||"").replace(/\.myshopify\.com$/,"");if(!saved||saved.state!==q.query.state||saved.shop!==shop)return r.status(400).send("Estado OAuth inválido.");if(q.query.error)return r.status(400).send("Autorización cancelada.");try{const x=await fetch(`https://${shop}.myshopify.com/admin/oauth/access_token`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.SHOPIFY_API_KEY,client_secret:process.env.SHOPIFY_API_SECRET,code:q.query.code})}),d=await x.json();if(!x.ok||!d.access_token)return r.status(502).send("No se pudo completar el inicio de sesión.");cookie(r,"tp_session",seal({shop,accessToken:d.access_token,createdAt:Date.now()}),86400);cookie(r,"tp_oauth_state","deleted",0);r.redirect("/?login=success")}catch(e){r.status(500).send("Error al completar el inicio de sesión.");}});
app.get("/api/session",(q,r)=>{const v=open(String((q.headers.cookie||"").match(/(?:^|; )tp_session=([^;]+)/)?.[1]||""));r.json(v?{authenticated:true,shop:v.shop}:{authenticated:false});});
export default app;
