import express from "express";
import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"200kb"}));
let strategy={enabled:true,mode:"simulation",collectionHandle:"men",fallback:"original",weights:{temperatureFit:30,countryAffinity:20,recentSales:20,newness:15,availability:15},exclusions:{excludeOutOfStock:true,preserveManualProducts:true},audit:{lastUpdated:null,lastApplied:null,lastAppliedBy:null}};
function normalizeWeights(w={}){const k=["temperatureFit","countryAffinity","recentSales","newness","availability"],v=Object.fromEntries(k.map(x=>[x,Math.max(0,Number(w[x]||0))])),t=Object.values(v).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(k.map(x=>[x,Math.round(v[x]/t*100)]));}
app.get("/api/health",(_q,r)=>r.json({ok:true,service:"trendsplant-ordering-app"}));
app.get("/api/strategy",(_q,r)=>r.json(strategy));
app.put("/api/strategy",(q,r)=>{strategy={...strategy,...q.body,weights:normalizeWeights(q.body?.weights||strategy.weights),audit:{...strategy.audit,lastUpdated:new Date().toISOString()}};r.json(strategy);});
app.post("/api/strategy/simulate",(q,r)=>{const c={country:q.body?.country||"ES",temperatureC:Number(q.body?.temperatureC??22),collectionHandle:strategy.collectionHandle},s=[["Essential T-Shirt","light",78],["Hooded Oversized Sweatshirt","warm",72],["Easy Denim Pants","mid",75],["Timber Corduroy Cap","accessory",68]],ranked=s.map(([title,type,baseScore],i)=>({id:"sample-"+(i+1),title,type,score:Math.min(100,baseScore+Math.round((((c.temperatureC>=25&&type==="light")||(c.temperatureC<=14&&type==="warm")?22:type==="mid"?8:0)*strategy.weights.temperatureFit/100)))})).sort((a,b)=>b.score-a.score);r.json({context:c,ranked,strategyVersion:strategy.audit.lastUpdated});});
app.post("/api/strategy/apply",(_q,r)=>{if(strategy.mode!=="live")return r.status(409).json({error:"La estrategia está en modo simulación. Cambia a live antes de aplicar."});strategy.audit={...strategy.audit,lastApplied:new Date().toISOString(),lastAppliedBy:"admin"};r.json({ok:true,message:"Aplicación preparada para el conector Shopify.",strategy});});
app.get("/auth/shopify",(q,r)=>{const shop=String(q.query.shop||"").replace(/\.myshopify\.com$/,"");if(!shop||!process.env.SHOPIFY_API_KEY||!process.env.SHOPIFY_APP_URL)return r.status(400).send("Faltan variables de Shopify.");const state=crypto.randomBytes(16).toString("hex"),scopes=encodeURIComponent(process.env.SHOPIFY_SCOPES||"read_products,write_products,read_inventory"),redirect=encodeURIComponent(process.env.SHOPIFY_APP_URL+"/auth/callback");r.redirect(`https://${shop}.myshopify.com/admin/oauth/authorize?client_id=${process.env.SHOPIFY_API_KEY}&scope=${scopes}&redirect_uri=${redirect}&state=${state}`);});
app.get("/auth/callback",(_q,r)=>r.status(501).send("OAuth callback pendiente."));
export default app;
